version: "3.4"

services:
  identifier:
    ports:
      - "80:80"
      
  triplestore:
    ports:
      - "8890:8890"

  poc-llm:
    ports:
      - "2000:80"

  ollama:
    ports:
      - "11434:11434"

  resource:
    ports:
      - "3000:80"